name: Publish Plugin to Github Releases
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        shell: bash
        run: |
          composer install --no-dev
          npm i

      - name: Build Library
        shell: bash
        run: npm run build:prod

      - name: Create WordPress Plugin Zip
        id: create-zip
        shell: bash
        run: |
          # Create a temporary directory for the plugin
          mkdir -p /tmp/onesearch/assets/build
          
          # Copy necessary files to the plugin directory
          cp -r build/ /tmp/onesearch/build/
          cp composer.json /tmp/onesearch/
          cp -r inc/ /tmp/onesearch/
          cp onesearch.php /tmp/onesearch/
          cp README.md /tmp/onesearch/
          cp uninstall.php /tmp/onesearch/
          cp -r vendor/ /tmp/onesearch/
          cp custom-functions.php /tmp/onesearch/
          
          # Create the zip file
          cd /tmp
          zip -r onesearch.zip onesearch/ -x "*.git*" "*.DS_Store*" "*node_modules*" "*tests*" "*test*"
          
          # Move zip to workspace
          mv onesearch.zip $GITHUB_WORKSPACE/
          
          # Set output for the zip path
          echo "zip-path=$GITHUB_WORKSPACE/onesearch.zip" >> $GITHUB_OUTPUT
          
          # Display zip contents for verification
          echo "=== Plugin zip contents ==="
          unzip -l $GITHUB_WORKSPACE/onesearch.zip

      - name: Upload Release Artifact with gh CLI
        if: startsWith(github.ref, 'refs/tags/dry') == false && github.ref != 'refs/heads/develop'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view "${{ github.ref_name }}" || \
            gh release create "${{ github.ref_name }}" \
              --title "${{ github.ref_name }}" \
              --generate-notes \
              --draft
          # Upload the artifact
          gh release upload "${{ github.ref_name }}" "${{ steps.create-zip.outputs.zip-path }}" --clobber
